user_token:

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: DB_USER
  password: DB_PASSWORD
  database: vkbot_qweez
bot:
  token: BOT_TOKEN
  group_id: BOT_GROUP_ID


