"""Added foreingKey word_id in GameModel

Revision ID: 32e3bd678a5d
Revises: 7ea0325c6e26
Create Date: 2023-04-01 13:03:16.890329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e3bd678a5d'
down_revision = '7ea0325c6e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'words', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'word_id')
    # ### end Alembic commands ###
