"""Added foreingKey chat_id in GameModel

Revision ID: 562e13cd9771
Revises: 32e3bd678a5d
Create Date: 2023-04-01 16:47:01.483000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562e13cd9771'
down_revision = '32e3bd678a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'games', 'chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.alter_column('games', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
