"""Added QwestionModel and update GameModel amd GameScoreModel

Revision ID: 7ea0325c6e26
Revises: 86224176ed81
Create Date: 2023-03-31 00:13:07.272575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea0325c6e26'
down_revision = '86224176ed81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.add_column('games', sa.Column('word', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('letters', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('current_move', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('games', sa.Column('is_winner', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_games_chat_id'), 'games', ['chat_id'], unique=False)
    op.add_column('gamescore', sa.Column('winner', sa.Boolean(), nullable=True))
    op.drop_column('gamescore', 'place')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamescore', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gamescore', 'winner')
    op.drop_index(op.f('ix_games_chat_id'), table_name='games')
    op.drop_column('games', 'is_winner')
    op.drop_column('games', 'is_active')
    op.drop_column('games', 'current_move')
    op.drop_column('games', 'letters')
    op.drop_column('games', 'word')
    op.drop_table('words')
    # ### end Alembic commands ###
